# Generated by Django 4.0.2 on 2022-02-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_merge_20220226_1527'),
        ('base', '0013_merge_20220226_1706'),
    ]

    operations = [
    ]
