# Generated by Django 4.0.2 on 2022-02-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_merge_20220226_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='No bio set.', max_length=200),
        ),
    ]
