# Generated by Django 4.0.2 on 2022-02-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(default='Uni of Exeter', max_length=200),
        ),
    ]
