# Generated by Django 4.0.2 on 2022-03-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_profile_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='placeholder.png', upload_to='base/resources'),
        ),
    ]
