# Generated by Django 4.0.2 on 2022-03-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='placeholder.png', upload_to='profile_pictures'),
        ),
    ]
