# Generated by Django 4.0.2 on 2022-03-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0019_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(default='No university set.', max_length=200),
        ),
    ]
