# Generated by Django 4.0.1 on 2022-02-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
