# Generated by Django 4.0.1 on 2022-02-20 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_challenges_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='likes',
            field=models.ManyToManyField(related_name='challengePost', to=settings.AUTH_USER_MODEL),
        ),
    ]
