# Generated by Django 4.0.1 on 2022-02-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_challenges_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='likes',
        ),
    ]
