# Generated by Django 4.0.1 on 2022-02-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0007_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='challenges',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
