# Generated by Django 4.0.1 on 2022-02-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0010_responses_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
