# Generated by Django 4.0.1 on 2022-02-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_profile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
