# Generated by Django 4.0.1 on 2022-02-26 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0009_accessattemptaddons'),
        ('base', '0012_alter_profile_points'),
    ]

    operations = [
    ]
