# Generated by Django 4.0.1 on 2022-02-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_responses_photograph'),
        ('base', '0015_responses_liked_likes'),
    ]

    operations = [
    ]
