# Generated by Django 4.0.1 on 2022-02-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_merge_20220228_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='photograph',
        ),
    ]
