# Generated by Django 4.0.2 on 2022-02-28 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_responses_photograph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_response', to='base.challenges'),
        ),
    ]
