# Generated by Django 4.0.1 on 2022-03-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_responses_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='No bio set.', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='profile_pictures/placeholder.png', upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(default='No university set.', max_length=200),
        ),
    ]
