# Generated by Django 4.0.1 on 2022-03-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_profile_bio_profile_picture_profile_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='photograph',
            field=models.ImageField(default='image_uploads/challenge-completed.png', upload_to='image_uploads/'),
        ),
    ]
