# Generated by Django 4.0.1 on 2022-03-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_weeklychallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='expires',
            field=models.DateTimeField(default='2025-01-01'),
        ),
    ]
