# Generated by Django 4.0.1 on 2022-03-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_challenges_expires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenges',
            old_name='expires',
            new_name='expires_on',
        ),
    ]
