# Generated by Django 4.0.1 on 2022-03-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_comments_user_alter_comments_response'),
        ('base', '0025_rename_expires_challenges_expires_on'),
    ]

    operations = [
    ]
