# Generated by Django 4.0.1 on 2022-03-15 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0027_remove_weeklychallenge_renewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
