# Generated by Django 4.0.1 on 2022-03-15 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_merge_20220315_1358'),
        ('base', '0029_alter_challenges_user'),
    ]

    operations = [
    ]
