# Generated by Django 4.0.1 on 2022-03-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_merge_20220315_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyChallenge',
        ),
    ]
