# Generated by Django 4.0.1 on 2022-03-16 14:58

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_profile_picture_delete_weeklychallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='photograph',
            field=models.ImageField(default='image_uploads/challenge-completed.png', upload_to=base.models.response_pic_location),
        ),
    ]
