# Generated by Django 4.0.1 on 2022-03-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_dailyriddle'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyriddle',
            name='points',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
