# Generated by Django 4.0.1 on 2022-03-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_completeriddle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completeriddle',
            old_name='challenge',
            new_name='riddle',
        ),
    ]
