# Generated by Django 4.0.1 on 2022-03-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_rename_challenge_completeriddle_riddle'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyriddle',
            name='answer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
