# Generated by Django 4.0.2 on 2022-03-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_profile_following'),
        ('base', '0037_reportcomments_reportposts_delete_report'),
    ]

    operations = [
    ]
